import type { Crane } from './types'

/**
 * Статический парк демо-стенда — 8 кранов.
 *
 * Источники значений:
 *  - макет «Главный экран» (массив RAW) — паспорт, место, итоги смены;
 *  - макет «Мониторинг крана v2» — текущие значения выбранного крана;
 *  - скриншоты рабочей системы, приложенные к макетам.
 * Подробнее об источниках — docs/02-sources.md.
 *
 * Это ЯКОРНЫЕ значения на момент DEMO_NOW (02.09.2026 11:39): генератор
 * телеметрии строит сутки так, чтобы сойтись именно к ним. Меняя число здесь,
 * помните про связанность: loadPct = massT / allowedT, а вылет и высота
 * считаются из длины стрелы и угла (см. telemetry.ts).
 */
export const FLEET: Crane[] = [
  {
    id: '2483580',
    name: 'SANY STC300T5',
    brand: 'SANY',
    plate: 'С 912 ХМ 196',
    status: 'work',
    operator: 'Смена 1 · Петров А.',
    place: 'Реж',
    coords: { lat: 57.37601, lon: 61.44039 },
    tempC: 14,
    windMs: 2.0,
    weather: 'Переменная облачность',
    visibility: 'хорошая',
    lastSeen: '4 мин назад',
    lastSeenMin: null,
    passport: {
      capacityT: 30,
      maxBoomM: 42.5,
      maxHeightM: 50.5,
      outriggers: '5,4 × 6,4 м',
      counterweightT: 6.2,
      totalHours: 1284,
      totalCycles: 8612,
      calibration: '12.08.2026',
      serviceInHours: 116,
    },
    current: {
      mode: 'load',
      loadPct: 62,
      massT: 18.6,
      allowedT: 30.0,
      boomAngleDeg: 68.26,
      boomLenM: 31.56,
      radiusM: 10.84,
      heightM: 29.4,
      azimuthDeg: 212,
      rpm: 1240,
      oilTempC: 84.0,
      coolantTempC: 78.5,
      hydPressureKpa: 12400,
      hydOilTempC: 56,
      fuelPct: 62,
      voltageV: 27.4,
      tiltXDeg: 0.42,
      tiltYDeg: 0.18,
    },
    shift: {
      workMin: 84.5,
      idleMin: 3,
      cycles: 6,
      liftedT: 9.82,
      overloads: 0,
      maxLoadPct: 88,
      avgCycleSec: 357,
    },
    systems: {
      can: 'ok',
      gps: 'ok',
      angle: 'ok',
      pressure: 'ok',
      link: 'ok',
      gsmDbm: -71,
      satellites: 12,
      trackPoints: 1639,
    },
    mapXY: [44, 46],
  },
  {
    id: '3026598',
    name: 'КС-45717К-3',
    brand: 'КАМАЗ',
    plate: 'М 178 ХК 86',
    status: 'alarm',
    operator: 'Смена 1 · Соколов В.',
    place: 'Угут',
    coords: { lat: 60.49641, lon: 74.25336 },
    tempC: 12,
    windMs: 6.0,
    weather: 'Преимущественно ясно',
    visibility: 'хорошая',
    lastSeen: '20 сек назад',
    lastSeenMin: null,
    passport: {
      capacityT: 25,
      maxBoomM: 21,
      maxHeightM: 21.4,
      outriggers: '5,6 × 4,95 м',
      counterweightT: 4.0,
      totalHours: 2460,
      totalCycles: 19480,
      calibration: '04.06.2026',
      serviceInHours: 12,
    },
    current: {
      mode: 'load',
      loadPct: 112,
      massT: 24.1,
      allowedT: 21.52,
      boomAngleDeg: 42.1,
      boomLenM: 18.2,
      radiusM: 12.6,
      heightM: 16.8,
      azimuthDeg: 96,
      rpm: 1480,
      oilTempC: 91.0,
      coolantTempC: 88.0,
      hydPressureKpa: 16800,
      hydOilTempC: 72,
      fuelPct: 38,
      voltageV: 27.1,
      tiltXDeg: 0.9,
      tiltYDeg: 0.54,
    },
    shift: {
      workMin: 191,
      idleMin: 11,
      cycles: 14,
      liftedT: 182.4,
      overloads: 2,
      maxLoadPct: 112,
      avgCycleSec: 405,
    },
    systems: {
      can: 'ok',
      gps: 'ok',
      angle: 'error',
      pressure: 'ok',
      link: 'ok',
      gsmDbm: -83,
      satellites: 9,
      trackPoints: 2140,
    },
    mapXY: [72, 20],
  },
  {
    id: '2487733',
    name: 'Zoomlion QY55V',
    brand: 'Zoomlion',
    plate: 'Т 118 ВС 66',
    status: 'warn',
    operator: 'Смена 1 · Гареев Р.',
    place: 'Нижний Тагил',
    coords: { lat: 57.9105, lon: 59.98122 },
    tempC: 11,
    windMs: 4.4,
    weather: 'Облачно',
    visibility: 'умеренная',
    lastSeen: '40 сек назад',
    lastSeenMin: null,
    passport: {
      capacityT: 55,
      maxBoomM: 42,
      maxHeightM: 58,
      outriggers: '6,8 × 6,4 м',
      counterweightT: 8.4,
      totalHours: 1902,
      totalCycles: 12336,
      calibration: '27.07.2026',
      serviceInHours: 240,
    },
    current: {
      mode: 'load',
      loadPct: 96,
      massT: 21.2,
      allowedT: 22.08,
      boomAngleDeg: 61.02,
      boomLenM: 24.4,
      radiusM: 11.9,
      heightM: 21.0,
      azimuthDeg: 148,
      rpm: 1360,
      oilTempC: 87.0,
      coolantTempC: 82.0,
      hydPressureKpa: 14900,
      hydOilTempC: 64,
      fuelPct: 54,
      voltageV: 27.6,
      tiltXDeg: 0.31,
      tiltYDeg: 0.22,
    },
    shift: {
      workMin: 108.9,
      idleMin: 2,
      cycles: 8,
      liftedT: 94.6,
      overloads: 0,
      maxLoadPct: 96,
      avgCycleSec: 372,
    },
    systems: {
      can: 'ok',
      gps: 'ok',
      angle: 'ok',
      pressure: 'warn',
      link: 'ok',
      gsmDbm: -78,
      satellites: 11,
      trackPoints: 1204,
    },
    mapXY: [30, 26],
  },
  {
    id: '2491204',
    name: 'Liebherr LTM 1050',
    brand: 'Liebherr',
    plate: 'К 402 РМ 96',
    status: 'work',
    operator: 'Смена 1 · Крылов Д.',
    place: 'Первоуральск',
    coords: { lat: 56.90812, lon: 59.94211 },
    tempC: 13,
    windMs: 3.1,
    weather: 'Малооблачно',
    visibility: 'хорошая',
    lastSeen: '1 мин назад',
    lastSeenMin: null,
    passport: {
      capacityT: 50,
      maxBoomM: 38,
      maxHeightM: 44,
      outriggers: '6,3 × 6,3 м',
      counterweightT: 7.6,
      totalHours: 3118,
      totalCycles: 24905,
      calibration: '19.05.2026',
      serviceInHours: 402,
    },
    current: {
      mode: 'load',
      loadPct: 74,
      massT: 18.6,
      allowedT: 25.14,
      boomAngleDeg: 55.4,
      boomLenM: 27.8,
      radiusM: 14.1,
      heightM: 24.2,
      azimuthDeg: 305,
      rpm: 1180,
      oilTempC: 81.0,
      coolantTempC: 76.0,
      hydPressureKpa: 11900,
      hydOilTempC: 58,
      fuelPct: 71,
      voltageV: 27.9,
      tiltXDeg: 0.12,
      tiltYDeg: 0.28,
    },
    shift: {
      workMin: 124.3,
      idleMin: 6,
      cycles: 11,
      liftedT: 121.0,
      overloads: 0,
      maxLoadPct: 88,
      avgCycleSec: 341,
    },
    systems: {
      can: 'ok',
      gps: 'ok',
      angle: 'ok',
      pressure: 'ok',
      link: 'ok',
      gsmDbm: -68,
      satellites: 13,
      trackPoints: 1877,
    },
    mapXY: [22, 52],
  },
  {
    id: '2492810',
    name: 'Ивановец КС-45717',
    brand: 'Ивановец',
    plate: 'Н 771 УК 66',
    status: 'idle',
    operator: 'Смена 1 · Ильин П.',
    place: 'Берёзовский',
    coords: { lat: 56.90512, lon: 60.79934 },
    tempC: 14,
    windMs: 1.2,
    weather: 'Ясно',
    visibility: 'хорошая',
    lastSeen: '2 мин назад',
    lastSeenMin: null,
    passport: {
      capacityT: 25,
      maxBoomM: 21,
      maxHeightM: 21.4,
      outriggers: '5,6 × 4,95 м',
      counterweightT: 4.0,
      totalHours: 864,
      totalCycles: 5210,
      calibration: '30.07.2026',
      serviceInHours: 318,
    },
    current: {
      mode: 'idle',
      loadPct: 0,
      massT: 0,
      allowedT: 15.0,
      boomAngleDeg: 12.0,
      boomLenM: 10.2,
      radiusM: 9.13,
      heightM: 2.22,
      azimuthDeg: 0,
      rpm: 780,
      oilTempC: 62.0,
      coolantTempC: 66.0,
      hydPressureKpa: 300,
      hydOilTempC: 41,
      fuelPct: 88,
      voltageV: 27.8,
      tiltXDeg: 0.05,
      tiltYDeg: 0.03,
    },
    shift: {
      workMin: 12.1,
      idleMin: 221,
      cycles: 1,
      liftedT: 6.2,
      overloads: 0,
      maxLoadPct: 18,
      avgCycleSec: 300,
    },
    systems: {
      can: 'ok',
      gps: 'ok',
      angle: 'ok',
      pressure: 'ok',
      link: 'ok',
      gsmDbm: -74,
      satellites: 10,
      trackPoints: 312,
    },
    mapXY: [44, 62],
  },
  {
    id: '2485607',
    name: 'XCMG XCT70S',
    brand: 'XCMG',
    plate: 'Х 329 ТТ 96',
    status: 'off',
    operator: '—',
    place: 'Шурала, г. Екатеринбург',
    coords: { lat: 57.45105, lon: 60.20623 },
    tempC: 15,
    windMs: 1.5,
    weather: 'Пасмурно',
    visibility: 'умеренная',
    lastSeen: '31.08.2026 14:33',
    lastSeenMin: -1,
    passport: {
      capacityT: 70,
      maxBoomM: 44.5,
      maxHeightM: 60.3,
      outriggers: '8,035 × 7,3 м',
      counterweightT: 12.0,
      totalHours: 2044,
      totalCycles: 14220,
      calibration: '11.03.2026',
      serviceInHours: -18,
    },
    current: {
      mode: 'off',
      loadPct: null,
      massT: 0,
      allowedT: 0,
      boomAngleDeg: 0,
      boomLenM: 0,
      radiusM: 0,
      heightM: 0,
      azimuthDeg: 0,
      rpm: 0,
      oilTempC: 0,
      coolantTempC: 0,
      hydPressureKpa: 0,
      hydOilTempC: 0,
      fuelPct: 0,
      voltageV: 0,
      tiltXDeg: 0,
      tiltYDeg: 0,
    },
    shift: {
      workMin: 0,
      idleMin: 1440,
      cycles: 0,
      liftedT: 0,
      overloads: 0,
      maxLoadPct: null,
      avgCycleSec: 0,
    },
    systems: {
      can: 'none',
      gps: 'none',
      angle: 'none',
      pressure: 'none',
      link: 'none',
      gsmDbm: null,
      satellites: null,
      trackPoints: 0,
    },
    mapXY: [30, 40],
  },
  {
    id: '2488121',
    name: 'Галичанин КС-55713',
    brand: 'Галичанин',
    plate: 'Р 205 ЕН 72',
    status: 'off',
    operator: '—',
    place: 'Тюмень',
    coords: { lat: 57.15302, lon: 65.5344 },
    tempC: 16,
    windMs: 2.8,
    weather: 'Переменная облачность',
    visibility: 'хорошая',
    lastSeen: '5 ч назад',
    lastSeenMin: 399,
    passport: {
      capacityT: 25,
      maxBoomM: 21.7,
      maxHeightM: 22,
      outriggers: '5,2 × 4,6 м',
      counterweightT: 4.2,
      totalHours: 1466,
      totalCycles: 9034,
      calibration: '22.04.2026',
      serviceInHours: 64,
    },
    current: {
      mode: 'off',
      loadPct: null,
      massT: 0,
      allowedT: 0,
      boomAngleDeg: 0,
      boomLenM: 0,
      radiusM: 0,
      heightM: 0,
      azimuthDeg: 0,
      rpm: 0,
      oilTempC: 0,
      coolantTempC: 0,
      hydPressureKpa: 0,
      hydOilTempC: 0,
      fuelPct: 0,
      voltageV: 0,
      tiltXDeg: 0,
      tiltYDeg: 0,
    },
    shift: {
      workMin: 0,
      idleMin: 566,
      cycles: 0,
      liftedT: 0,
      overloads: 0,
      maxLoadPct: null,
      avgCycleSec: 0,
    },
    systems: {
      can: 'none',
      gps: 'ok',
      angle: 'none',
      pressure: 'none',
      link: 'none',
      gsmDbm: -95,
      satellites: 6,
      trackPoints: 88,
    },
    mapXY: [58, 74],
  },
  {
    id: '2490455',
    name: 'Tadano GR-250N',
    brand: 'Tadano',
    plate: 'О 640 АХ 86',
    status: 'off',
    operator: '—',
    place: 'Сургут',
    coords: { lat: 61.25401, lon: 73.39621 },
    tempC: 9,
    windMs: 5.2,
    weather: 'Дождь',
    visibility: 'плохая',
    lastSeen: '11 ч назад',
    lastSeenMin: 39,
    passport: {
      capacityT: 25,
      maxBoomM: 30.5,
      maxHeightM: 41,
      outriggers: '5,8 × 6,1 м',
      counterweightT: 4.6,
      totalHours: 1120,
      totalCycles: 7480,
      calibration: '08.02.2026',
      serviceInHours: 96,
    },
    current: {
      mode: 'off',
      loadPct: null,
      massT: 0,
      allowedT: 0,
      boomAngleDeg: 0,
      boomLenM: 0,
      radiusM: 0,
      heightM: 0,
      azimuthDeg: 0,
      rpm: 0,
      oilTempC: 0,
      coolantTempC: 0,
      hydPressureKpa: 0,
      hydOilTempC: 0,
      fuelPct: 0,
      voltageV: 0,
      tiltXDeg: 0,
      tiltYDeg: 0,
    },
    shift: {
      workMin: 31.7,
      idleMin: 662,
      cycles: 2,
      liftedT: 12.8,
      overloads: 0,
      maxLoadPct: 45,
      avgCycleSec: 480,
    },
    systems: {
      can: 'none',
      gps: 'none',
      angle: 'none',
      pressure: 'none',
      link: 'none',
      gsmDbm: null,
      satellites: null,
      trackPoints: 640,
    },
    mapXY: [70, 8],
  },
]

export const DEFAULT_CRANE_ID = '2483580'

export function getCrane(id: string): Crane {
  return FLEET.find((c) => c.id === id) ?? (FLEET[0] as Crane)
}

/** Подписи и палитра статусов — используются в чипах, точках и легендах. */
export const STATUS_META = {
  work: {
    label: 'В работе',
    dot: 'var(--ok)',
    bg: 'var(--ok-bg)',
    fg: 'var(--ok-text)',
    border: 'var(--border)',
  },
  alarm: {
    label: 'Перегруз',
    dot: 'var(--danger)',
    bg: 'var(--danger-bg)',
    fg: 'var(--danger-text)',
    border: 'var(--danger-border)',
  },
  warn: {
    label: '90–105%',
    dot: 'var(--warn)',
    bg: 'var(--warn-bg)',
    fg: 'var(--warn-text)',
    border: '#f4dda6',
  },
  idle: {
    label: 'Простой',
    dot: 'var(--warn)',
    bg: 'var(--surface-neutral)',
    fg: 'var(--ink-3)',
    border: 'var(--border)',
  },
  off: {
    label: 'Нет связи',
    dot: 'var(--neutral)',
    bg: 'var(--surface-neutral)',
    fg: 'var(--ink-4)',
    border: 'var(--border)',
  },
} as const

export const SYS_META = {
  ok: { label: 'OK', color: 'var(--ok-text)' },
  warn: { label: 'Предупр.', color: 'var(--warn)' },
  error: { label: 'Ошибка', color: 'var(--danger)' },
  none: { label: 'Нет', color: 'var(--ink-muted)' },
} as const
